// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/easy_send.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<bool> Function(ApprovalRequest)
  dco_decode_DartFn_Inputs_approval_request_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  RustStreamSink<List<DeviceSnapshot>>
  dco_decode_StreamSink_list_device_snapshot_Sse(dynamic raw);

  @protected
  RustStreamSink<SavedFileEvent> dco_decode_StreamSink_saved_file_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SendEvent> dco_decode_StreamSink_send_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApprovalRequest dco_decode_approval_request(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NodeConfig dco_decode_box_autoadd_node_config(dynamic raw);

  @protected
  SendTarget dco_decode_box_autoadd_send_target(dynamic raw);

  @protected
  DeviceSnapshot dco_decode_device_snapshot(dynamic raw);

  @protected
  FileItem dco_decode_file_item(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DeviceSnapshot> dco_decode_list_device_snapshot(dynamic raw);

  @protected
  List<FileItem> dco_decode_list_file_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TrustedDeviceView> dco_decode_list_trusted_device_view(dynamic raw);

  @protected
  NodeConfig dco_decode_node_config(dynamic raw);

  @protected
  NodeStatus dco_decode_node_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SavedFileEvent dco_decode_saved_file_event(dynamic raw);

  @protected
  SendEvent dco_decode_send_event(dynamic raw);

  @protected
  SendPhase dco_decode_send_phase(dynamic raw);

  @protected
  SendTarget dco_decode_send_target(dynamic raw);

  @protected
  TrustedDeviceView dco_decode_trusted_device_view(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  RustStreamSink<List<DeviceSnapshot>>
  sse_decode_StreamSink_list_device_snapshot_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SavedFileEvent> sse_decode_StreamSink_saved_file_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SendEvent> sse_decode_StreamSink_send_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApprovalRequest sse_decode_approval_request(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NodeConfig sse_decode_box_autoadd_node_config(SseDeserializer deserializer);

  @protected
  SendTarget sse_decode_box_autoadd_send_target(SseDeserializer deserializer);

  @protected
  DeviceSnapshot sse_decode_device_snapshot(SseDeserializer deserializer);

  @protected
  FileItem sse_decode_file_item(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DeviceSnapshot> sse_decode_list_device_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<FileItem> sse_decode_list_file_item(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TrustedDeviceView> sse_decode_list_trusted_device_view(
    SseDeserializer deserializer,
  );

  @protected
  NodeConfig sse_decode_node_config(SseDeserializer deserializer);

  @protected
  NodeStatus sse_decode_node_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SavedFileEvent sse_decode_saved_file_event(SseDeserializer deserializer);

  @protected
  SendEvent sse_decode_send_event(SseDeserializer deserializer);

  @protected
  SendPhase sse_decode_send_phase(SseDeserializer deserializer);

  @protected
  SendTarget sse_decode_send_target(SseDeserializer deserializer);

  @protected
  TrustedDeviceView sse_decode_trusted_device_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_approval_request_Output_bool_AnyhowException(
    FutureOr<bool> Function(ApprovalRequest) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_list_device_snapshot_Sse(
    RustStreamSink<List<DeviceSnapshot>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_saved_file_event_Sse(
    RustStreamSink<SavedFileEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_send_event_Sse(
    RustStreamSink<SendEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_approval_request(
    ApprovalRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_node_config(
    NodeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_send_target(
    SendTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_snapshot(
    DeviceSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_item(FileItem self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_device_snapshot(
    List<DeviceSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_item(List<FileItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trusted_device_view(
    List<TrustedDeviceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_config(NodeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_node_status(NodeStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_saved_file_event(
    SavedFileEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_event(SendEvent self, SseSerializer serializer);

  @protected
  void sse_encode_send_phase(SendPhase self, SseSerializer serializer);

  @protected
  void sse_encode_send_target(SendTarget self, SseSerializer serializer);

  @protected
  void sse_encode_trusted_device_view(
    TrustedDeviceView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
