// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `approval_request_of`, `current`, `failed`, `of`, `send_failure_message`, `snapshot_of`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Node`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`

Future<NodeStatus> nodeStart({
  required NodeConfig config,
  required FutureOr<bool> Function(ApprovalRequest) onApproval,
}) => RustLib.instance.api.crateApiEasySendNodeStart(
  config: config,
  onApproval: onApproval,
);

Future<void> nodeStop() => RustLib.instance.api.crateApiEasySendNodeStop();

Future<void> nodeAnnounce() =>
    RustLib.instance.api.crateApiEasySendNodeAnnounce();

Stream<List<DeviceSnapshot>> nodeDeviceEvents() =>
    RustLib.instance.api.crateApiEasySendNodeDeviceEvents();

Stream<SavedFileEvent> nodeSavedEvents() =>
    RustLib.instance.api.crateApiEasySendNodeSavedEvents();

Future<List<TrustedDeviceView>> trustList() =>
    RustLib.instance.api.crateApiEasySendTrustList();

Future<bool> trustContains({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiEasySendTrustContains(fingerprint: fingerprint);

Future<void> trustAdd({required String fingerprint, required String alias}) =>
    RustLib.instance.api.crateApiEasySendTrustAdd(
      fingerprint: fingerprint,
      alias: alias,
    );

Future<void> trustRemove({required String fingerprint}) =>
    RustLib.instance.api.crateApiEasySendTrustRemove(fingerprint: fingerprint);

Future<DeviceSnapshot> manualExchangeInfo({
  required String address,
  required int port,
}) => RustLib.instance.api.crateApiEasySendManualExchangeInfo(
  address: address,
  port: port,
);

Stream<SendEvent> sendFiles({
  required SendTarget target,
  required List<String> paths,
}) => RustLib.instance.api.crateApiEasySendSendFiles(
  target: target,
  paths: paths,
);

Future<void> sendCancel() => RustLib.instance.api.crateApiEasySendSendCancel();

class ApprovalRequest {
  final String senderAlias;
  final String senderFingerprint;
  final bool isNewDevice;
  final List<FileItem> files;

  const ApprovalRequest({
    required this.senderAlias,
    required this.senderFingerprint,
    required this.isNewDevice,
    required this.files,
  });

  @override
  int get hashCode =>
      senderAlias.hashCode ^
      senderFingerprint.hashCode ^
      isNewDevice.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApprovalRequest &&
          runtimeType == other.runtimeType &&
          senderAlias == other.senderAlias &&
          senderFingerprint == other.senderFingerprint &&
          isNewDevice == other.isNewDevice &&
          files == other.files;
}

class DeviceSnapshot {
  final String alias;
  final String deviceType;
  final String fingerprint;
  final String ip;
  final int port;

  const DeviceSnapshot({
    required this.alias,
    required this.deviceType,
    required this.fingerprint,
    required this.ip,
    required this.port,
  });

  @override
  int get hashCode =>
      alias.hashCode ^
      deviceType.hashCode ^
      fingerprint.hashCode ^
      ip.hashCode ^
      port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSnapshot &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          deviceType == other.deviceType &&
          fingerprint == other.fingerprint &&
          ip == other.ip &&
          port == other.port;
}

class FileItem {
  final String id;
  final String name;
  final PlatformInt64 size;

  const FileItem({required this.id, required this.name, required this.size});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size;
}

class NodeConfig {
  final String baseDir;
  final String saveDir;
  final String alias;
  final String deviceType;

  const NodeConfig({
    required this.baseDir,
    required this.saveDir,
    required this.alias,
    required this.deviceType,
  });

  @override
  int get hashCode =>
      baseDir.hashCode ^
      saveDir.hashCode ^
      alias.hashCode ^
      deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeConfig &&
          runtimeType == other.runtimeType &&
          baseDir == other.baseDir &&
          saveDir == other.saveDir &&
          alias == other.alias &&
          deviceType == other.deviceType;
}

class NodeStatus {
  final int port;
  final String fingerprint;

  const NodeStatus({required this.port, required this.fingerprint});

  @override
  int get hashCode => port.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeStatus &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          fingerprint == other.fingerprint;
}

class SavedFileEvent {
  final String path;
  final String fromAlias;

  const SavedFileEvent({required this.path, required this.fromAlias});

  @override
  int get hashCode => path.hashCode ^ fromAlias.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedFileEvent &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fromAlias == other.fromAlias;
}

class SendEvent {
  final SendPhase phase;
  final int fileIndex;
  final int fileCount;
  final String fileName;
  final PlatformInt64 sentBytes;
  final PlatformInt64 totalBytes;
  final String? message;

  const SendEvent({
    required this.phase,
    required this.fileIndex,
    required this.fileCount,
    required this.fileName,
    required this.sentBytes,
    required this.totalBytes,
    this.message,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      fileIndex.hashCode ^
      fileCount.hashCode ^
      fileName.hashCode ^
      sentBytes.hashCode ^
      totalBytes.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          fileIndex == other.fileIndex &&
          fileCount == other.fileCount &&
          fileName == other.fileName &&
          sentBytes == other.sentBytes &&
          totalBytes == other.totalBytes &&
          message == other.message;
}

enum SendPhase { waitingApproval, uploading, done, failed, canceled }

class SendTarget {
  final String ip;
  final int port;
  final String fingerprint;
  final String alias;

  const SendTarget({
    required this.ip,
    required this.port,
    required this.fingerprint,
    required this.alias,
  });

  @override
  int get hashCode =>
      ip.hashCode ^ port.hashCode ^ fingerprint.hashCode ^ alias.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTarget &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          port == other.port &&
          fingerprint == other.fingerprint &&
          alias == other.alias;
}

class TrustedDeviceView {
  final String fingerprint;
  final String alias;
  final String trustedAt;

  const TrustedDeviceView({
    required this.fingerprint,
    required this.alias,
    required this.trustedAt,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^ alias.hashCode ^ trustedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedDeviceView &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          alias == other.alias &&
          trustedAt == other.trustedAt;
}
